version: "3.7"
services:
  client:
    container_name: ctru_client
    restart: always
    environment:
      - /config/development.env
    build:
      context: .
      dockerfile: dockerfile-client
    volumes:
      - ./:/app/client
      - /app/client/node_modules/
    ports:
      - "3000:3000"
    tty: true
    working_dir: /app/client
